### ISSUE TITLE
"from paramiko_expect import SSHClientInteraction" fails to load library

### ISSUE THREAD

**Issue by ryangurazov** [fgimian/paramiko-expect#18]
Hi, 

You might want to look into this since other people can run into this

pip-installed module

```
[qa-user@qa-driver ~]$ sudo pip install git+https://github.com/fgimian/paramiko-expect.git
[sudo] password for qa-user: 
Collecting git+https://github.com/fgimian/paramiko-expect.git
  Cloning https://github.com/fgimian/paramiko-expect.git to /tmp/pip-aqFZmx-build
Requirement already satisfied (use --upgrade to upgrade): paramiko>=1.10.1 in /usr/lib/python2.7/site-packages (from paramiko-expect==0.2)
Requirement already satisfied (use --upgrade to upgrade): cryptography>=1.1 in /usr/lib64/python2.7/site-packages (from paramiko>=1.10.1->paramiko-expect==0.2)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /usr/lib/python2.7/site-packages (from paramiko>=1.10.1->paramiko-expect==0.2)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko>=1.10.1->paramiko-expect==0.2)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko>=1.10.1->paramiko-expect==0.2)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko>=1.10.1->paramiko-expect==0.2)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko>=1.10.1->paramiko-expect==0.2)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko>=1.10.1->paramiko-expect==0.2)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in /usr/lib64/python2.7/site-packages (from cryptography>=1.1->paramiko>=1.10.1->paramiko-expect==0.2)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography>=1.1->paramiko>=1.10.1->paramiko-expect==0.2)
Installing collected packages: paramiko-expect
  Running setup.py install for paramiko-expect ... done
Successfully installed paramiko-expect-0.2

```

it was placed in the right location, although for some reason `from paramiko_expect import SSHClientInteraction` fails:

```
[qa-user@qa-driver ~]$ sudo pip show paramiko-expect
---
Metadata-Version: 1.0
Name: paramiko-expect
Version: 0.2
Summary: An expect-like extension for the Paramiko SSH library
Home-page: https://github.com/fgimian/paramiko-expect
Author: Fotis Gimian
Author-email: fgimiansoftware@gmail.com
License: MIT
Location: /usr/lib/python2.7/site-packages
Requires: paramiko
Classifiers:

[qa-user@qa-driver ~]$ python paramiko_expect.pyc 
Traceback (most recent call last):
  File "paramiko_expect.py", line 3, in <module>
    from paramiko_expect import SSHClientInteraction
  File "/home/qa-user/paramiko_expect.py", line 3, in <module>
    from paramiko_expect import SSHClientInteraction
ImportError: cannot import name SSHClientInteraction

```

There is no problem with `import paramiko` that is also located in same directory: `/usr/lib/python2.7/site-packages` 

```
[qa-user@qa-driver ~]$ sudo pip show paramiko
---
Metadata-Version: 2.0
Name: paramiko
Version: 2.1.1
Summary: SSH2 protocol library
Home-page: https://github.com/paramiko/paramiko/
Author: Jeff Forcier
Author-email: jeff@bitprophet.org
Installer: pip
License: LGPL
Location: /usr/lib/python2.7/site-packages
Requires: cryptography, pyasn1
Classifiers:
  Development Status :: 5 - Production/Stable
  Intended Audience :: Developers
  License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)
  Operating System :: OS Independent
  Topic :: Internet
  Topic :: Security :: Cryptography
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.2
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
```

and it does not look like permission issue either:

```
[qa-user@qa-driver ~]$ sudo python paramiko_expect.pyc 
Traceback (most recent call last):
  File "paramiko_expect.py", line 3, in <module>
    from paramiko_expect import SSHClientInteraction
  File "/home/qa-user/paramiko_expect.py", line 3, in <module>
    from paramiko_expect import SSHClientInteraction
ImportError: cannot import name SSHClientInteraction
```

**Comment by ryangurazov** [comment]
OK, the irony of all this was that to test out `paramiko_expect` module I used script named `paramiko_expect.py`. Just occurred to me and changing script test script name was the issue :)
Basically name clash
