### ISSUE TITLE
Expect function not matching 

### ISSUE THREAD

**Issue by talbiston** [fgimian/paramiko-expect#6]
I really like this module but im running into an issue getting the "expect" function to work correctly. 
It seems as though its not reading the data form the buffer. Im no Python Wiz so im not totally sure 
what the issue is but i can supply the error. 

The code Logs in to the router just fine and the prompt i will get back is "FW80CM3911602851 #" 
in my out put i do get "FW80CM3911602851 #" displayed back to the console but expect never 
matches the out put. 

im just matching this exactly just to make sure its matching correctly .. The issue is it dose not seem to be working . 

Below is my testing code: 

#!/usr/bin/python2
import paramiko
from paramikoe import SSHClientInteraction
import traceback

def Main():

    try:

        hostname = 'example.us'
        username = 'Uname'      
        password = 'passWord'  

        s = paramiko.SSHClient()
        s.load_system_host_keys()
        s.set_missing_host_key_policy(paramiko.AutoAddPolicy())

        s.connect(hostname=hostname, username=username, password=password)
        interact = SSHClientInteraction(s, timeout=10, display=True)
        if interact.expect(re_strings='FW80CM3911602851 # ', timeout=60):
            print "passed"

    except Exception:
        traceback.print_exc()
    finally:
        try:
            s.close()
        except:
            pass

if __name__ == "__main__":
    Main()
__author__ = 'todd'

Out put =

/usr/bin/python2.7 /home/todd/PycharmProjects/paramikoe-test/Main.py
FW80CM3911602851 #

 Traceback (most recent call last):
  File "/home/todd/PycharmProjects/paramikoe-test/Main.py", line 24, in Main
    if interact.expect(re_strings='.FW80CM3911602851 # ', timeout=60):
  File "/usr/local/lib/python2.7/dist-packages/paramikoe.py", line 122, in expect
    buffer = self.channel.recv(self.buffer_size)
  File "/usr/lib/python2.7/dist-packages/paramiko/channel.py", line 619, in recv
    raise socket.timeout()
timeout

Process finished with exit code 0

**Comment by talbiston** [comment]
I noticed that there was a similar  issue reported before and yo had aasked for the Prompt output 
to be directed to a file. so i have that info for you . 

todd@fox:~$ ssh TRG@hymie.us > router-prompt.txt

todd@fox:~$ cat router-prompt.txt 
FW80CM3911602851 # exit

**Comment by talbiston** [comment]
I just noticed that i may have not been using the code correctly so i updated my code. I am still getting the exact same results though . 

import paramiko
from paramikoe import SSHClientInteraction
import traceback


def Main():

    try:

        hostname = 'hymie.us'
        username = 'TRG'      #raw_input('username: ')
        password = 'N0cm2nadm'  #getpass.getpass('password: ')

        s = paramiko.SSHClient()
        s.load_system_host_keys()
        s.set_missing_host_key_policy(paramiko.AutoAddPolicy())

        s.connect(hostname=hostname, username=username, password=password)
        interact = SSHClientInteraction(s, timeout=10, display=True)
        test = interact.expect(re_strings='FW80CM3911602851 #')
        if test == 1:
            print "passed"
    except Exception:
        traceback.print_exc()
    finally:
        try:
            s.close()
        except:
            pass

if __name__ == "__main__":
    Main()
