### ISSUE TITLE
Error : Undefined symbol "SSLv3_client_method"

### ISSUE THREAD

**Issue by oijkn** [fgimian/paramiko-expect#91]
Hello, I'm trying to connect to a Cisco device but I get the following error message, do you have a solution, please ?

```sh
Traceback (most recent call last):
  File "/opt/test/cisco-pbb.py", line 26, in <module>
    import paramiko
  File "/usr/local/lib/python3.8/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 132, in <module>
    class Transport(threading.Thread, ClosingContextManager):
  File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 206, in Transport
    if KexCurve25519.is_available():
  File "/usr/local/lib/python3.8/site-packages/paramiko/kex_curve25519.py", line 30, in is_available
    X25519PrivateKey.generate()
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/x25519.py", line 39, in generate
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 63, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /usr/local/lib/python3.8/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: Undefined symbol "SSLv3_client_method"
```

Thank you in advance for you reply.

**Comment by fruch** [comment]
This looks like an issue with your installation of paramiko, not sure how it's related to this package.

**Comment by oijkn** [comment]
OK, I will try to reinstall it.
